#!/usr/bin/python3


import argparse
import configparser
import sys


# FIXME unhardcoded years
# FIXME show urls
# FIXME show titles
# FIXME load only once


def dont_yet_have(filename, year):
    srcfile = configparser.ConfigParser()
    srcfile.read(filename)
    return (str(year) not in srcfile.sections())


def parse_args(args):
    parser = argparse.ArgumentParser()
    parser.add_argument("source_files", nargs="+")
    return parser.parse_args(args)


def main():
    years_wanted = [2019, 2020]
    args = parse_args(sys.argv[1:])
    for filename in args.source_files:
        for year in years_wanted:
            if dont_yet_have(filename, year):
                print("Missing %s in %s" % (year, filename))


if __name__ == '__main__':
    main()
