
[general]
title = The Monarch's Official Birthday
# Normally 3rd Sat in June in the UK for Charles III.
# Around the Commonwealth it happens on different days.
# (normally 2nd Sat in June for Elizabeth II)
usually = Jun

[2026]
title = The King's Official Birthday
# Hmm... some parts of the Internet were expecting it to be the 20th (3rd Sat)
# but then he celebrated with Trooping the Colour on the 13th (2nd Sat).
# It would REALLY help if the palace clearly published it somewhere!
#date = 2026-06-20
date = 2026-06-13

[2025]
title = The King's Official Birthday
date = 2025-06-21

[2024]
title = The King's Official Birthday
date = 2024-06-15

[2023]
title = The King's Official Birthday
date = 2023-06-17
